packages:
  - 'apps/*'
  - 'packages/*'

overrides:
  content-security-policy-parser: 0.6.0
  form-data: 4.0.6
  msgpackr: 1.10.1
  vite: 6.4.3
  ws: 8.21.0

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
